name: 'Test'

on:
  workflow_dispatch:
  push:

jobs:
  test-jinx:
    runs-on: ubuntu-22.04
    steps:
      - name: "checkout"
        uses: actions/checkout@v3
        with:
          ref: ${{ env.GITHUB_REF }}
      - name: "run tests"
        run: |
          go test -v ./...
